### ISSUE TITLE
[Feature Request] config.json should be ignored

### ISSUE THREAD

**Issue by wywywywy** [Zyin055/Config-Presets#10]
In my opinion the `config.json` file should be added to `.gitignore`, so that users' changes won't be overwritten.

If needed, there can also be a `config.json.example` file so that users know how to configure it even if they've modified the `config.json` file.

**Comment by Zyin055** [comment]
24639a5c7cf87eeb4ac9b61e4df6e093fafb5720

config.json is now created with default values on first startup. Added to gitignore so users can make changes and update without the changes being overwritten.
