### ISSUE TITLE
You're copying my code without permission or a license. Please remove

### ISSUE THREAD

**Issue by Gerschel** [Zyin055/Config-Presets#12]
![image](https://user-images.githubusercontent.com/9631031/209053566-8033ee8c-1f07-4547-aef6-e98b9b85ba72.png)

**Comment by Gerschel** [comment]
Here's the commit you copied it from. It took me hours to develop write and debug.  
commit b124209292f46b996a99b49fb0688ae2eb8f825a

**Comment by Zyin055** [comment]
I don't understand, that `save_config()` function from your screenshot is a heavily modified version of the code that you committed to this repo on December 13th: https://github.com/Zyin055/Config-Presets/pull/5

**Comment by Gerschel** [comment]
What you have in your code is not from pull request I closed, in which I closed because you have a license that claims copyright on the work and don't provide a contributors agreement. You copied from my project.

**Comment by Gerschel** [comment]
def save_config

def func

new_settings  

You even got my name on it 

From my project that you copied from commit b124209292f46b996a99b49fb0688ae2eb8f825a:  
![image](https://user-images.githubusercontent.com/9631031/209067024-ec6a56cc-31a3-46e7-a125-2658ea988354.png)

**Comment by Gerschel** [comment]
Right here you say I came up with it.  
https://github.com/Zyin055/Config-Presets/blob/main/scripts/config_presets.py#L334  

I know exactly what you did not go through to get there, because I had comprehensions and modified it to work for detailed saving, and it took me 13 hours to put together, 5 hours in research and 8 hours of coding to rewrite my stuff to work as needed.

**Comment by Gerschel** [comment]
You just stripped some stuff and renamed some things.

This is the `closed by me because of licensing issues` request you are talking about. 

![image](https://user-images.githubusercontent.com/9631031/209067854-9a600c3d-d67e-44ef-ad5d-e49a00f1ecf6.png)

**Comment by Gerschel** [comment]
I asked if you wanted to collaborate, I mentioned a license issue. You never responed to my concerns, but copied my stuff while you chose a license where you can claim copyright, but could not honor mine.
![image](https://user-images.githubusercontent.com/9631031/209068163-d8c2eea7-9a91-412f-a974-0bd29a804e2c.png)

**Comment by Gerschel** [comment]
Heavily modified does not count. Read how to get out from under a copyright, it is a 100% rewrite. Changing some names do not count.

**Comment by Zyin055** [comment]
1. Your [sd_web_ui_preset_utils](https://github.com/Gerschel/sd_web_ui_preset_utils) project was published 2 days AFTER you exposed the code in https://github.com/Zyin055/Config-Presets/pull/5 to this repo. Saying I copied from your project (which doesn't even have a license on it) is nonsensical.
2. You never asked me if I wanted to collaborate. Go reread https://github.com/Zyin055/Config-Presets/pull/5 . You had simply started contributing code to this open source project.
3. MIT license is the most open license there is. It's not restricting you from doing anything.

I don't understand what the fuss is about. You contributed code, you had second thoughts and stopped contributing. None of this is affected by the MIT license or the non existent license on your project.
