### ISSUE TITLE
Just because I made that repo public then doesn't mean I didnt have a private one and work on this specific thing

### ISSUE THREAD

**Issue by Gerschel** [Zyin055/Config-Presets#13]
https://github.com/Zyin055/Config-Presets/issues/12

What time frame is this, two weeks ago. -> https://github.com/gradio-app/gradio/discussions/2769

updated last week -> https://gist.github.com/Gerschel/51a0e2a9089795ff399f9e346ae68085

You obviously copied my shit, you say so, just because I went from byte code to clear code in the public doesn't mean I don't have it documented that I am the developer. I have my time stamped comitts.

**Comment by Gerschel** [comment]
Right here is a video of me working on presets. 
https://github.com/gradio-app/gradio/discussions/2795

**Comment by Gerschel** [comment]
That was the day before you put yours up. So obviously I was working on it before I helped you.

**Comment by Zyin055** [comment]
The other issue was locked, please don't create new issues to bypass it.
