### ISSUE TITLE
Not setting width/height

### ISSUE THREAD

**Issue by jhogsett** [Zyin055/Config-Presets#16]
This is a great idea, a feature I've wanted for a while. I've installed it and so far just I'm just using the default presets. Unfortunately when I do, it does not change the output width/height (but does set the other generation params). I'm not sure what to do to make it work. I've disabled it for now but hoping for some help.

**Comment by halr9000** [comment]
Same here. My very first idea to use this extension for was to make it easier to flip between SD 2.1 @ 768x768 and other models optimized for 512. It seems to work for most or all of the other settings except for the ones I need! :) 

There's no obvious troubleshooting I know to do, and no errors appear in the console.

**Comment by Zyin055** [comment]
I updated my A1111 to the latest version and they made some big changes. They renamed Highres. Fix, Removed firstpass width/height and replaced it with a single dropdown, and removed the checkbox selection for samples.

Working on fixes now.

**Comment by Zyin055** [comment]
Try updating both the Config Presets extension and your Automatic1111 install and see if the issue is resolved.

**Comment by jhogsett** [comment]
@Zyin055 confirmed working. Thank you!
