### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by jhogsett** [Zyin055/Config-Presets#17]
The extension is working great, tyvm! I have a couple feature requests:

1. When "default" is the currently selected config and I've manually made changes to the UI, like changing steps, it would be nice if choosing "default" again would force it back to those default settings. What I notice now is it seems to ignore the request, maybe because no actual change is being made in the UI. This may be an HTML/Gradio side issue that's not fixable directly, though an "apply" button might help.
2. It would be nice if settings that are not present in the preset config JSON are left untouched when that preset is selected and applied. What I noticed is: I created a series of presets solely to set width, height and upscaling. I deleted unrelated settings like batch size. When I applied the preset, I noticed it reverted my batch size from "8" to "1".

**Comment by Zyin055** [comment]
1. The dropdown uses a Gradio .change() event. Selecting the same dropdown element does not trigger that event, and to my knowledge there isn't a way to do that within the constraints of Gradio. If I could somehow call a Python function from Javascript then it'd be doable.
2. This is the functionality that I wanted to have from day one, but once again Gradio won't let me do it. If anyone can figure out a way to do it, I'd love to see a pull request.

So yeah, Gradio is kinda strict in what it lets you do. I personally don't like it very much.
