### ISSUE TITLE
compatibility issue with new web ui?

### ISSUE THREAD

**Issue by catalpaaa** [Zyin055/Config-Presets#18]
when boot on the newest webui

> [ERROR][Config-Presets] The component 'txt2img_height' no longer exists in the Web UI. Try updating the Config-Presets extension. This extension will not work until this issue is resolved.
[ERROR][Config-Presets] The component 'img2img_steps' no longer exists in the Web UI. Try updating the Config-Presets extension. This extension will not work until this issue is resolved.

**Comment by Zyin055** [comment]
I haven't been updating my A1111 installation recently because of the recent bugs around TI training and new requirements causing issues. I'll probably check back in on this in a week or two, so until then if you wanna keep using the extension just downgrade your A1111 install to your previous version.

**Comment by Zyin055** [comment]
Reopening to remind me to check it later when I update.

**Comment by Zyin055** [comment]
Are you still getting this error after updating to the latest A1111 commit?

I just updated to this A1111 version and am not getting any errors and everything works as expected:
```
commit 226d840e84c5f306350b0681945989b86760e616 (HEAD -> master, origin/master, origin/HEAD)
Merge: 07edf574 fb58fa62
Author: AUTOMATIC1111 <16777216c@gmail.com>
Date:   Wed Feb 1 16:30:28 2023 +0300

    Merge pull request #7334 from EllangoK/master

    X/Y/Z plot now saves sub grids if opts.grid_save and honors draw_legend
```

**Comment by catalpaaa** [comment]
nah, maybe A1111 screwed up something last commit
