### ISSUE TITLE
Firstpass width and firstpass height settings may be necessary

### ISSUE THREAD

**Issue by MiyatoKyo** [Zyin055/Config-Presets#2]
It is known that if the aspect ratio of the original resolution and the resolution of the highres fix are aligned, it is possible to fix the highres without changing the composition.
For example, the workflow is as follows. If I get good results with 768x512, I turn on highres fix and set first pass to 768x512 and resolution to 1536x1024.

**Comment by Zyin055** [comment]
Added with 1992e1eed76bda3de93719faf8d82c7c5ac9afa1
