### ISSUE TITLE
Feature request: Save the Highres Fix width and height

### ISSUE THREAD

**Issue by SeanBannister** [Zyin055/Config-Presets#28]
Thanks for this extension, certainly something I was looking for.

It'd be awesome if it was possible to save the width and height listed under Highres Fix, currently it's only possible to save the Upscale ratio but in my use case I would prefer to use the width and height instead as the ratio doesn't get me to the exact dimensions I need.

![image](https://user-images.githubusercontent.com/197231/224267493-2ff4978b-cfe0-46d0-92d5-4b79e22b742c.png)

**Comment by Zyin055** [comment]
The ability to add these fields has been added in the latest update. You can add them using the "Add custom fields..." button when creating a new config preset.
