### ISSUE TITLE
Working on save feature now

### ISSUE THREAD

**Issue by Gerschel** [Zyin055/Config-Presets#3]

**Comment by Gerschel** [comment]
Save feature complete, script needs names reformatted in json to work with the rest of the code.

**Comment by Gerschel** [comment]
Alright, so it works completely, except that, it saves it as the default names the webui uses, so not only does the json need reformatting, all the names need to be updated to by in sync with the internal names. Or, we create an extra map

**Comment by Zyin055** [comment]
Using internal names is better so that we can move away from being reliant on the English localizations.

**Comment by Gerschel** [comment]
![image](https://user-images.githubusercontent.com/9631031/207471617-887b00bd-4b2e-43bf-9672-70653e1112f2.png)
![image](https://user-images.githubusercontent.com/9631031/207471704-0f499485-ba33-4cb6-a540-e542580e9d09.png)

It wouldn't take me long to do it. But I might not have enough time to refactor it tonight or tommorrow, wifes birthday.

We would still have hardcoded names, as our filter relies on it. It would be interesting to see how the localization changes the names, see if there's a way to dynamically replace the initializing list with their localization.

**Comment by Gerschel** [comment]
Looks like it's just on the front-end. It might be that only the js needs be updated, might not. It's worth a test after name refactor. Localization would be another milestone.

**Comment by bai0012** [comment]
Good job, maybe this can also set functions like enable face restore or choosing models

**Comment by Gerschel** [comment]
Update: the debug issue below was because I was a dumbass and turned up basic logging to debug and forgot.

I got haulted. Script just flat out stopped working. Some weird bugs started happening with my computer. Like half the file disappearing. Cmd prompt had some bug. Files stopped saving.  
I had a bunch of pending windows updates, so I cleaned things up and rebooted.  

My file was back.  
But it wasn't working.  
So I tried a few times. Then it started working again.  

Now, I think something updated and I get a bunch of errors, not related to my task, it's in the apps self update with git clone (no extra pulls added by me, I micromanage my installs), and gradio flips in to debug mode.  

![image](https://user-images.githubusercontent.com/9631031/207513020-e4a8cfc0-0323-407e-906a-11453bdc4b31.png)

I had to revert back to a file I knew was fine, I was in the middle of a milestone with this one, I think I'm going to push it online, then finish with the milestone and redo the changes I had before all this.

**Comment by Gerschel** [comment]
This one is a wip, give it a test: The old config file wont work. Make a save, text field was just slapped in at a random place (bottom), then see if the save applies/refills like it's suppose to.  https://github.com/Zyin055/Config-Presets/pull/5

You can use my restart button in the scripts section, to quickly restart. https://github.com/Gerschel/stable-diffusion-webui-restart-button  

The current feature I was in the middle of; dropdown updates and text field clears once save has been pressed. But would be in gray color, but primary when theres text in the name field.
Delete preset button.
