### ISSUE TITLE
Feature request: SD upscale script (img2img)

### ISSUE THREAD

**Issue by Stibo** [Zyin055/Config-Presets#31]
It would be nice if the script selection and SD upscale options would be saved too. I think that would be reasonable, because its a "core"-script? I get the idea that scripts are not saved, because they are too individual. But I think the SD upscale script is the most used and it would be helpful if those settings (overlap, scale factor and upscaler) would be stored in the preset too.

**Comment by shiloh92** [comment]
I also would love this feature. I find it cumbersome to fiddle with SD upscale settings every time - a setting that works great (once discovered) should be savable to preset. Thank you if you can.

**Comment by Zyin055** [comment]
The ability to add these fields has been added in the latest update. You can add them using the "Add custom fields..." button when creating a new config preset.
