### ISSUE TITLE
Is there any way to store additional information added by the extension?

### ISSUE THREAD

**Issue by snuff8729** [Zyin055/Config-Presets#32]
I'm using additional extensions like Dynamic Thresholding, Detection Detailer . Is there a way to include them and save them?

**Comment by Zyin055** [comment]
The ability to add these fields has been added in the latest update. You can add them using the "Add custom fields..." button when creating a new config preset as long as the extension developer labeled those components with a unique ID.

**Comment by MoreColors123** [comment]
I can't get it to work with a paremeter of the Seed Travel script though. In the html the parameter "Step" is labeled with id=component-5890, but as soon as i add that in your plugin's config-txt-file, the dropdown isn't showing up anymore. 
Thanks for making this possible anyway!

**Comment by Zyin055** [comment]
"component-5890" is not a valid ID. It is an ID generated by Gradio because the extension's developer did not assign it a unique ID. You should make a request to the extension's developer to assign it a unique ID, like "script_seed_travel_step" or something.
