### ISSUE TITLE
Feature request: allow customisable component IDs

### ISSUE THREAD

**Issue by wywywywy** [Zyin055/Config-Presets#34]
Currently, the list of component IDs that this extension can control is hardcoded in the script.

This should be made into a config file, so users can customise what they want to store, such as parameters of extensions.

This will also satisfy issues #31 #32 (but maybe not #28 & #29 because they are more complicated).

**Comment by Zyin055** [comment]
Resolved by adding the "Add custom fields..." button when creating a new config preset.
