### ISSUE TITLE
Prompt and Negative Prompt

### ISSUE THREAD

**Issue by ghost** [Zyin055/Config-Presets#36]
I think being able to put prompt and negative prompt to the config preset would be helpful as some checkpoint models actually require you to enter specific positive or negative prompts to make it work correctly.

https://civitai.com/models/1250/the-simpsons this one for example needs "asim style" for the prompt to make it work.

I don't know about anyone else, but I definitely struggle with remembering all the quirks of some of the models I have and this feature would save lot of looking stuff up when I could just have it in a preset already for me.

And I think it would also enhance this suggestion: https://github.com/Zyin055/Config-Presets/issues/4
Although I'm fine without it autoswitching the models, I can do that myself and just name the preset after the model I should be using for each preset

**Comment by Zyin055** [comment]
The ability to add the prompt/negative prompt to a config preset was added a few days ago. You can use the new "Add tracked fields..." button to track those fields and use them when creating a preset.

But due to the technical complexity the selected model cannot be changed in this way.
