### ISSUE TITLE
[Feature Request] ControlNet Support

### ISSUE THREAD

**Issue by Ev-Bro** [Zyin055/Config-Presets#37]
It would be great if ControlNet support was added. So I can easily save ControlNet's preprocessor, model, weight, Ending Control Step. I tried following the instructions to create the custom entries, but failed. Thank you!

**Comment by Zyin055** [comment]
I was also hoping to do that when I added the "Add tracked fields..." button a few days ago, but ControlNet does not label their components with IDs, so it's impossible for Config Presets to target them.

Perhaps you could make an issue on the ControlNet extension's github asking them to uniqely label their components with IDs (with `elem_id="..."`) so other extensions can interact with them.

**Comment by Ev-Bro** [comment]
Ok good to know! I might do that. Or just suggest they build in presets lol.

**Comment by altoiddealer** [comment]
I just spotted that they have an open PR to address this issue.  Hopefully they commit sooner than later!

https://github.com/Mikubill/sd-webui-controlnet/pull/1206


*Edit* They just merged it… IDs are there now, but they don't just appear in ui-config.json.
I'm not sure what the best method is to find them, but I was able to find them via Chrome's Inspect Element, then in Elements tab > Properties.  Example of one: txt2img_controlnet_ControlNet-2_controlnet_enable_checkbox

<img width="1843" alt="Screenshot 2023-05-13 070039" src="https://github.com/Zyin055/Config-Presets/assets/1613484/43a15520-5d21-44d8-9eb4-f2a6f97722ae">

**Comment by altoiddealer** [comment]
It's beautiful :D

<img width="700" alt="ControlNet Toggles" src="https://github.com/Zyin055/Config-Presets/assets/1613484/072fdb21-8c82-4bae-a47e-3029e2df1e30">

**Comment by Ev-Bro** [comment]
Nice!
