### ISSUE TITLE
Type hints TypeError

### ISSUE THREAD

**Issue by h43lb1t0** [Zyin055/Config-Presets#38]
`def load_txt2img_custom_tracked_component_ids() -> list[str]:
TypeError: 'type' object is not subscriptable`
i can't create a pull request.
`from typing import List` and change `list[str]` to `List[str]`

**Comment by Zyin055** [comment]
What version of Python are you loading with Stable Diffusion? It says on the first line when booting up A1111.

I'm on 3.10.6 and no errors here.

**Comment by h43lb1t0** [comment]
I'm still on Python 3.8.10 for A1111. the extension still works. But I'm always getting this error at startup.

**Comment by Zyin055** [comment]
That's the issue. The [minimum recommended Python version](https://github.com/AUTOMATIC1111/stable-diffusion-webui#automatic-installation-on-windows) is 3.10.6, so I won't make code changes to address your error.
