### ISSUE TITLE
Possible to track AlwaysOn script expanders? (e.g., ControlNet)

### ISSUE THREAD

**Issue by marcsyp** [Zyin055/Config-Presets#43]
Is it possible to add support for AlwaysOn Script expanders (open/close state)?  Tried adding the ControlNet expander to the track components and got errors:

![image](https://github.com/Zyin055/Config-Presets/assets/2940820/3fcd0f4b-c503-4582-aba2-0d9c6e11dee6)

**Comment by Zyin055** [comment]
To my understanding, the expandable accordions that extensions like ControlNet use are not real components. Although they are created in the Python code as a Gradio component, their behavior appears to be controlled on the client side, which means that Config Presets in it's current state cannot control them.
