### ISSUE TITLE
Preset for "Tiled Diffusion & VAE" and "StableSR"

### ISSUE THREAD

**Issue by mikheys** [Zyin055/Config-Presets#46]
Good afternoon. Please tell me how can I save the settings for the "Tiled Diffusion & VAE" and "StableSR" extensions?

**Comment by Zyin055** [comment]
You use the "Add custom fields..." button to modify the config text file to include the IDs of the components you want to add. IDs are found in the HTML of the browser (F12).

For example, StableSR in the img2img tab uses these IDs:

```
StableSR-scale
StableSR-color-fix
StableSR-save-original
StableSR-pure-noise
```

**Comment by mikheys** [comment]
All identifiers are of the form component-xxxxx(((
Although in the new automation in the settings you can save all these settings as default. Maybe somehow it can be solved?

**Comment by Zyin055** [comment]
See screenshot for an example of how to get the correct ID.

![Clipboard01](https://github.com/Zyin055/Config-Presets/assets/5003647/03bda86e-ac15-41fc-ad94-3f15f799f577)

**Comment by mikheys** [comment]
![image](https://github.com/Zyin055/Config-Presets/assets/34010273/d40823e5-9984-4e37-bbdf-8a1cc34d1a39)
![image](https://github.com/Zyin055/Config-Presets/assets/34010273/1251aa8a-8cef-46b8-84ec-6c1d3ac327bb)
![image](https://github.com/Zyin055/Config-Presets/assets/34010273/4dfdf1f2-77bc-415f-afef-703b44e33184)

what am I doing wrong?

**Comment by Zyin055** [comment]
Did you save the config file and reload the UI?

**Comment by mikheys** [comment]
of course

**Comment by Zyin055** [comment]
Did you add that ID as a tracked component in the other config file?

![Clipboard01](https://github.com/Zyin055/Config-Presets/assets/5003647/e52676dd-8e1c-40ae-b5b8-e7de48b0c422)
![Clipboard02](https://github.com/Zyin055/Config-Presets/assets/5003647/df8263e7-0031-446b-819b-cef2cd568c1c)

**Comment by mikheys** [comment]
![image](https://github.com/Zyin055/Config-Presets/assets/34010273/e005ecc3-2e39-4ec7-97f9-d7c62bb7515b)
![image](https://github.com/Zyin055/Config-Presets/assets/34010273/bab97a4a-93dd-407b-b28e-ea4f13af76de)

I add a new entry manually and the CD does not load at all. Could you write a complete list of all these elements to add to the file for this extension?

**Comment by Zyin055** [comment]
Read the error: you are missing a comma at the end of line 44. It's invalid JSON format. I recommend you stick to using the GUI to make your preset config file instead of manually editing it yourself.

**Comment by mikheys** [comment]
Thanks a lot for the tip! Please write all the possible settings for this extension, so as not to catch them manually. If there is such an opportunity. Thank you very much in advance!

**Comment by Zyin055** [comment]
I can't possibly write every ID for every extension. I have included a list of IDs for popular extensions in the config file by default, but that config file is only created with those new IDs for new users.

**Comment by mikheys** [comment]
Understood thanks!

**Comment by mikheys** [comment]
Here's what I got. Everything is working! Only for this it didn't work:
![image](https://github.com/Zyin055/Config-Presets/assets/34010273/156ff4f1-f843-430b-b181-c2073a56df31)

# StableSR (extension)
StableSR-scale
StableSR-color-fix
StableSR-save-original
StableSR-pure-noise

# Tiled Diffusion (extension)
MD-i2i-enabled
MD-i2i-keep-input-size
MD-i2i-method
MD-i2i-control-tensor-cpu
MD-i2i-latent-tile-width
MD-i2i-latent-tile-height
MD-i2i-latent-tile-overlap
MD-i2i-latent-tile-batch-size
MD-i2i-upscaler-index
MD-i2i-upscaler-factor

# Tiled Diffusion - Noise Inversion
MD-i2i-noise-inverse
MD-i2i-noise-inverse-steps
MD-i2i-noise-inverse-retouch
MD-i2i-noise-inverse-renoise-strength
MD-i2i-noise-inverse-renoise-kernel

# Tiled VAE
tiledvae-i2i-enable
tiledvae-i2i-vae2gpu
tiledvae-i2i-enc-size
tiledvae-i2i-dec-size
tiledvae-i2i-fastenc
tiledvae-i2i-fastenc-colorfix
tiledvae-i2i-fastdec

**Comment by Zyin055** [comment]
https://github.com/pkuliyi2015/sd-webui-stablesr/issues/24
Made a request to StableSR to give the SR Model a unique ID.

**Comment by Westernnero** [comment]
Hi Zyin055! I've been using your extension and I really appreicate your work!

However, may I ask that if there's an ID like "txt2img_enable_hr" which, when True, makes the dropdown box shown as dropped down? 

I am using Tiled Diffusion & VAE as well. The other IDs worked. But the dropdown box will not change (Though when you manually drop it down you can see the checkbox checked correctly).

It's OK if there's no such function, but it will be better if it has. Thank you very much.

**Comment by Zyin055** [comment]
@Westernnero I don't understand exactly what you're asking for.

Before A1111 1.6.0 the hires fix checkbox was labeled as `txt2img_enable_hr`. After 1.6.0 the checkbox was changed to an accordion (and a hidden checkbox) with ID of `txt2img_hr-checkbox` which works as a config preset.

**Comment by Westernnero** [comment]
![image](https://github.com/Zyin055/Config-Presets/assets/40510735/1122e410-28e6-4226-a298-ca238b101654)
This is the 'dropdown box' I meant.
As for Hires fix, when I change the Config Preset, the Hires fix dropbox can be shown or hidden as the preset changes.

However, since Tiled Diffusion is an extension, I don't know if its 'box' can be manipulated like this.

That is my question. Sorry for the ambiguous part.

**Comment by Zyin055** [comment]
The technical term for that "dropdown box" is an accordion.

The only reason the hires accordion can be controlled in 1.6.0+ is because they use a hidden checkbox which can be controlled by Config Presets. It's a custom built accordion component by A1111. The out of the box accordion component that Gradio provides does not have that. So in order for it to be controlled, the Tiled Diffusion author would need to use the same component type that the hires fix uses which includes a hidden checkbox.

**Comment by Westernnero** [comment]
OK, thank you very much!

**Comment by Westernnero** [comment]
Hi Zyin, the old IDs for Tiled Diffusion - Tiled VAE elements changed so Config Preset would not be loaded. I tried to find the new IDs for the elements and they should be fine. Please consider contain them in the new default config files. The old ones look like "tiledvae-i2i-XXXX". Here's the new ones:

MD-i2i-enable
MD-i2i-vae2gpu
MD-i2i-enc-size
MD-i2i-dec-size
MD-i2i-fastenc
MD-i2i-fastenc-colorfix
MD-i2i-fastdec
