### ISSUE TITLE
Cannot re-apply the current preset.

### ISSUE THREAD

**Issue by Westernnero** [Zyin055/Config-Presets#49]
I've been using this ext for a while and I really like it!
However, here's the thing: if i want to change the preset, it's ok. But if I want to use the preset which is already there (the one showing in the box), it does not apply to my WebUI.
I dont know if this is a bug or not. Sometimes I changed some settings in my WebUI and then I want to use the preset I usually use. So I have to change to another preset then change it back. Because if you see a preset shown in the box, it cannot be applied by just clicking it.

Is it possible that, whatever preset I choose in the pull-down menu, it just applies.

I'm using the lastest A1111 SD webui (1.4.0) with python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: N/A  •  gradio: 3.32.0

**Comment by Zyin055** [comment]
I'm aware of this behavior and I don't think it's something I can fix. It's cause Gradio sucks - it doesn't fire the dropdown change event if the selected element is the same, and there's no parameter to change this behavior.

I recommend using a blank preset called "None", and select that before reselecting the desired preset.

**Comment by Westernnero** [comment]
thank you for your reply. So unfortunately. Seems that we've to wait for a
gradio update to get this fixed.



Zyin055 ***@***.***> 于 2023年7月3日周一 07:03写道：
