### ISSUE TITLE
[Feature request] Ultimate SD upscale script (img2img)

### ISSUE THREAD

**Issue by Erehr** [Zyin055/Config-Presets#51]
There's support for SD upscale script but can the same be added for Ultimate SD upscale?
[https://github.com/Coyote-A/ultimate-upscale-for-automatic1111](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111)

**Comment by Zyin055** [comment]
The author of Ultimate SD upscale needs to update their code to include IDs on their components so that Config Presets can control them. You need to make an issue in their repo, this isn't something that I can fix.

**Comment by wywywywy** [comment]
I've created a new PR to add the element IDs in: https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/pull/117

**Comment by Clonephaze** [comment]
Ultimate SD upscale's recent [update](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/commit/728ffcec7fa69c83b9e653bf5b96932acdce750f) gave 16 (I think) element IDs. 
Here's the list in a format you can just copy into your img2img tracked components.txt file: 
```
# Ultimate SD Upscaler
#ultimateupscale_target_size_type
#ultimateupscale_custom_width
#ultimateupscale_custom_height
#ultimateupscale_custom_scale
#ultimateupscale_upscaler_index
#ultimateupscale_redraw_mode
#ultimateupscale_tile_width
#ultimateupscale_tile_height
#ultimateupscale_mask_blur
#ultimateupscale_padding
#ultimateupscale_seams_fix_type
#ultimateupscale_seams_fix_denoise
#ultimateupscale_seams_fix_width
#ultimateupscale_seams_fix_mask_blur
#ultimateupscale_seams_fix_padding
#ultimateupscale_save_upscaled_image
#ultimateupscale_save_seams_fix_image
```
