### ISSUE TITLE
SD.Next Second Pass change fixes.

### ISSUE THREAD

**Issue by brknsoul** [Zyin055/Config-Presets#52]
Edit the file `automatic\extensions\Config-Presets\scripts\config_presets.py` 

Hit Ctrl+F and find `self.txt2img_component_ids`

Change
`txt2img_hr_upscaler` to `txt2img_sampling_alt`
and
`txt2img_hires_steps` to `txt2img_steps_alt`

**Comment by Zyin055** [comment]
This should hopefully be resolved now after merging PR https://github.com/Zyin055/Config-Presets/pull/55 . If it is then you can close this issue.
