### ISSUE TITLE
Save Script name instead of index

### ISSUE THREAD

**Issue by marcsyp** [Zyin055/Config-Presets#59]
Hi there -- great work on this plugin, I believe it is absolutely essential for any serious workflow with A1111.  Only one thing persistently gives me headaches, and that is that the script list is stored as an index value, which easily changes whenever you add or remove plugins, or revert to older configurations of A1111, etc.  This results in exceptions or the wrong script being selected, which is a dealbreaker for workflow. 

It would be great if the script could be stored as a string field with the script's name (as these do not change often if at all), which would be used to search the existing installed scripts and select the first instance of the script with the stored name that is found.  If the name is not found, it would fail gracefully.  This would prevent problems with name collisions (if that's even possible) and with missing scripts due to configuration (although the plugin won't load properly if the script is missing and being tracked, which is a separate issue).

The logic should include a fallback for older configuration files that are still using index values, a simple test for an int should suffice, otherwise the string logic is used.  For upgrading purposes, it could be as simple as loading in a known good configuration where all configurations are loading properly, and then rewriting the configurations one by one to update to the string field.  An Update all button would be great which performs a search and replace, although diligent users can search and replace themselves in a text editor.

Any thoughts?  I'm not as familiar with the backend code to know whether there are any obstacles to implementing this, but I think it would provide a much improved and more stable experience.  thx

**Comment by marcsyp** [comment]
Incidentally, one big improvement in the meantime is to do a check on whether the index of the list exists so that there is no exception and all the other element_id values get set properly anyway -- the user would just have to manually change the script to the one desired.  As it stands, the exception of an index higher than the script list item count causes no values to be set, which is rough.  Thanks.

**Comment by marcsyp** [comment]
Working Example:

'def config_preset_dropdown_change(dropdown_value, *components_value):
                            config_preset = config_presets[dropdown_value]
                            print(f"[Config-Presets] Changed to: {dropdown_value}")

                            # update component values with user preset
                            current_components = dict(zip(component_map.keys(), components_value))
                            #print("Components before:", current_components)
                            current_components.update(config_preset)

                            # transform necessary components from index to value
                            for component_name, component_value in current_components.items():
                                #print(component_name, component_value)
                                if component_name in index_type_components and type(component_value) == int:
                                        if (component_value < len(component_map[component_name].choices)):        # <--------------
                                            current_components[component_name] = component_map[component_name].choices[component_value]

                            #print("Components after :", current_components)
                            
                            return list(current_components.values())'

**Comment by wywywywy** [comment]
Sorry how do you mean? You can already specify the script name. It does have to be a number.

```
{
    "Ultimate SD Upscale": {
        "script_list": "Ultimate SD upscale"
    }
}
```

**Comment by marcsyp** [comment]
Yes, exactly -- currently it is stored as an int (index position of the script in the list when the configuration was saved), but if it were stored as the name of the script, as you have demonstrated, the CP logic would need a special IF block to handle the script_list field and search for the name of the script in the list of choices and convert that to the index position, then passing that to the component if an index was found.

**Comment by wywywywy** [comment]
I meant to say it does **NOT** have to be a number. Setting it to a name already works (though bear in mind it's case sensitive).

This line handles it already.

```
current_components.update(config_preset)
```
