### ISSUE TITLE
Face Restore Option

### ISSUE THREAD

**Issue by koriekhov** [Zyin055/Config-Presets#6]
Hi!
Would it be possible to add option to activate "Restore faces" on txt2img and img2img ? 
That would be almost full set of preset settings and just great.

Thanks for your work.

**Comment by Gerschel** [comment]
Got it, will push into current pull request.

**Comment by Zyin055** [comment]
I'm hesitant to add too many fields to the presets since it reduces their flexibility.

If I could find a way in the code to not update components if they are omitted from the config then then I'd consider it, but I can't figure out how to do that.

**Comment by Jonseed** [comment]
I agree that face restore would be a good enhancement to add to a config preset.

**Comment by Zyin055** [comment]
Restore faces can now be used as a config preset.
