### ISSUE TITLE
aDetailer Section Now Broken - Extension Load Fails

### ISSUE THREAD

**Issue by abline11** [Zyin055/Config-Presets#68]
I've just loaded the LATEST version of this extension on the LATEST version of Automatic1111 and the extensions refuses to load up on restart. The message in the console is:

[ERROR][Config Presets] The txt2img component 'script_txt2img_adetailer_ad_inpaint_full_res' could not be processed. This may be because you are running an outdated version of the Config-Presets extension, you included a component ID in the custom tracked components config file that does not exist, it no longer exists (if you updated an extension or Automatic1111), or is an invalid component (if this is the case, you need to manually edit the config file at C:\AI\stable-diffusion-webui\extensions\Config-Presets\config-txt2img-custom-tracked-components.txt or just delete it so it resets to defaults). This extension will not work until this issue is resolved.

It seems to be caused by the aDetailer Section on these entries:

script_txt2img_adetailer_ad_inpaint_full_res
script_txt2img_adetailer_ad_inpaint_full_res_padding
script_txt2img_adetailer_ad_inpaint_full_res_2nd
script_txt2img_adetailer_ad_inpaint_full_res_padding_2nd

Is this a known problem??

**Comment by Zyin055** [comment]
New update with https://github.com/Zyin055/Config-Presets/commit/d3ecee690ce61e4e5312493d3a9bb80d08abc06d https://github.com/Zyin055/Config-Presets/commit/74d21bae6275abce7e9f2b8c1e5d6911caeaeeda should fix this. ADetailer changed one of their IDs back on 6/04/23, causing this to break. I added a fix so that it auto updates the old IDs to the new ones at runtime. You can also change the `ad_inpaint_full_res` IDs to `ad_inpaint_only_masked` in your custom fields file manually if you want to.

**Comment by abline11** [comment]
Hi, 

 

Thanks for your quick response.  

 

Unfortunately, you have added a ‘script_txt2img_adetailer_ad_use_inpaint_width_height’ but not a ‘script_txt2img_adetailer_ad_use_inpaint_width_height_2nd’ to the COMPONENT TXT file.

 

So that still causes a problem with the second aDetailer instance.

 

Kind regards,

 

Andrew Brown

**Comment by Zyin055** [comment]
There is a `script_txt2img_adetailer_ad_use_inpaint_width_height_2nd` line in the custom fields file. You likely have a version of that file that was generated before we added it. You can either add `script_txt2img_adetailer_ad_use_inpaint_width_height_2nd` manually or delete the file so it's regenerated with that field included.

https://github.com/Zyin055/Config-Presets/blob/main/scripts/config_presets.py#L218

**Comment by abline11** [comment]
Thanks again. I added it manually and it now works. Sent from my iPhoneOn 14 Oct 2023, at 23:48, Zyin055 ***@***.***> wrote:﻿
There is a script_txt2img_adetailer_ad_use_inpaint_width_height_2nd line in the custom fields file. You likely have a version of that file that was generated before we added it. You can either add script_txt2img_adetailer_ad_use_inpaint_width_height_2nd manually or delete the file so it's regenerated with that field included.
https://github.com/Zyin055/Config-Presets/blob/main/scripts/config_presets.py#L218

**Comment by abline11** [comment]
Unfortunately. I have exactly the same problem on the Img2Img tab now ‘script_img2img_adetailer_ad_inpaint_full _res’ could not be processed. Should I raise another new issue?On 15 Oct 2023, at 17:36, Zyin055 ***@***.***> wrote:﻿
Closed #68 as completed.

**Comment by Zyin055** [comment]
Same issue. Rename the old `inpaint_full_res` IDs to `inpaint_only_masked`.
