### ISSUE TITLE
Custom Options not applying

### ISSUE THREAD

**Issue by UltraBlackLinux** [Zyin055/Config-Presets#70]
so I've got these two blocks in my config (extensions/Config-Presets/config-txt2img.json), but it just doesn't apply many of the settings. The openposer settings block is completely ignored and the prompt value is also ignored. Any idea what's going on?
I've updated both A1111 and all extensions
Thanks!

```json
    "Openpose-Poser": {
        "txt2img_controlnet_ControlNet-0_controlnet_enable_checkbox": true,
        "txt2img_controlnet_ControlNet-0_controlnet_low_vram_checkbox": true,
        "txt2img_controlnet_ControlNet-0_controlnet_pixel_perfect_checkbox": true,
        "txt2img_controlnet_ControlNet-0_controlnet_preprocessor_dropdown": "none",
        "txt2img_controlnet_ControlNet-0_controlnet_model_dropdown": "control_v11p_sd15_openpose",
        "txt2img_controlnet_ControlNet-0_controlnet_control_mode_radio": "OpenPose"
    },
    "Superspeed-SD15": {
        "txt2img_prompt": "<lora:LCM_LoRA_Weights_SD15:0.8>",
        "txt2img_sampling": "Euler",
        "txt2img_width": 800,
        "txt2img_height": 800,
        "txt2img_steps": 5,
        "txt2img_batch_count": 2,
        "txt2img_cfg_scale": 2
    },

```

**Comment by Zyin055** [comment]
I just tested it with your presets and it is working on my end. I'm using Automatic1111 1.6.0 (not the dev branch) and the most recent Config Presets.

Are you getting any errors in the console?

For the controlnet one, make sure to uncomment out the relevant fields in `config-txt2img-custom-tracked-components.txt` so it knows to look for those components:
```
# ControlNet (extension):
txt2img_controlnet_ControlNet-0_controlnet_enable_checkbox
txt2img_controlnet_ControlNet-0_controlnet_low_vram_checkbox
txt2img_controlnet_ControlNet-0_controlnet_pixel_perfect_checkbox
txt2img_controlnet_ControlNet-0_controlnet_preprocessor_preview_checkbox
txt2img_controlnet_ControlNet-0_controlnet_preprocessor_dropdown
txt2img_controlnet_ControlNet-0_controlnet_model_dropdown
txt2img_controlnet_ControlNet-0_controlnet_control_weight_slider
txt2img_controlnet_ControlNet-0_controlnet_start_control_step_slider
txt2img_controlnet_ControlNet-0_controlnet_ending_control_step_slider
txt2img_controlnet_ControlNet-0_controlnet_control_mode_radio
txt2img_controlnet_ControlNet-0_controlnet_resize_mode_radio
txt2img_controlnet_ControlNet-0_controlnet_automatically_send_generated_images_checkbox
```

Unrelated, but for your Superspeed-SD15 preset you should be using the LCM sampler instead of Euler. The most updated version of AnimateDiff supplies this LCM sampler, and hopefully soon will be incorporated into base A1111.

**Comment by UltraBlackLinux** [comment]
> make sure to uncomment out the relevant fields in `config-txt2img-custom-tracked-components.txt` so it knows to look for those components:

Oh i was under the impression that I was supposed to copy out the names of the fields and just paste them into my config. 
Now that I removed the comments on the important fields it's actually working, almost. The control type still does not apply (even though I looked at the config and confirmed that it read the correct value on save): 
![image](https://github.com/Zyin055/Config-Presets/assets/62404294/45600a93-4935-474d-9b4a-4166230e4a3d)
Now, something peculiar I noticed: In the config it's called `  txt2img_controlnet_ControlNet-0_controlnet_control_mode_radio`, however in the html it's called `  txt2img_controlnet_ControlNet-0_controlnet_type_filter_radio`. Maybe the problem resides here?

> Unrelated, but for your Superspeed-SD15 preset you should be using the LCM sampler instead of Euler. The most updated version of AnimateDiff supplies this LCM sampler, and hopefully soon will be incorporated into base A1111.

I actually checked all samplers and LCM produced a bad image.

```
Euler
Euler a
DPM2 a
DPM++ SDE
DPM++ SDE Karrays
DPM++ 2S a
DPM++ 2S a Karras
DPM++ 2M SDE
DPM++ 3M SDE
```
These are the samplers that worked best for me, for SD 1.5 at least. I have noticed that SDXL likes Euler a more than Euler. That probably applies to other cases as well

**Comment by Zyin055** [comment]
`txt2img_controlnet_ControlNet-0_controlnet_control_mode_radio` is for the 3 "Control Mode" buttons.
`txt2img_controlnet_ControlNet-0_controlnet_type_filter_radio` is for the 19 "Control Type" buttons.

Regardless, type_filter_radio was missing from the default `config-txt2img-custom-tracked-components.txt` file, so I added it to the default config file to help people in the future. For now you can add `txt2img_controlnet_ControlNet-0_controlnet_type_filter_radio` as a line in the file manually yourself to use it.

**Comment by UltraBlackLinux** [comment]
> For now you can add `txt2img_controlnet_ControlNet-0_controlnet_type_filter_radio` as a line in the file manually yourself to use it.

I actually tried that but it told me that it couldn't find the controls or something like that, stating that I'm maybe running an outdated version.
I wonder if I did something wrong....
