### ISSUE TITLE
Feature request: Override setting field.

### ISSUE THREAD

**Issue by nykwil** [Zyin055/Config-Presets#71]
I know that clip skip, vae, checkpoint can't be set. But have you looked into the override field? Which can have values for all of those.

Thanks essential extension.

![image](https://github.com/Zyin055/Config-Presets/assets/1003128/cc1196cb-df2f-472c-bd1d-3d9d99b4a98d)

**Comment by Zyin055** [comment]
I haven't tried controlling that component specifically, but it's a multi-select field which is not supported.
