### ISSUE TITLE
Confused on how to populate aDetailer fields in the add preset feature.

### ISSUE THREAD

**Issue by ryenots** [Zyin055/Config-Presets#72]
Hopefully this is a simple question, after installing Config-Presets, I wanted to add aDetailer fields to a new preset. I do not see any aDetailer fields present among the check boxes of regular txt2img fields. What do i need to do for these to appear? I could not find any info on this in any other git issue, or online. If needed I can provide screenshots or any other info.

**Comment by Zyin055** [comment]
Click the "Add/Remove..." button, then click "Add custom fields...". A text file will open that you can edit to include ADetailer fields.

**Comment by ryenots** [comment]
Okay, but where do I find what actually needs to be put into this text file for each of the fields to populate?

**Comment by Zyin055** [comment]
Instructions are at the top of the text file.

```
# Put custom txt2img tracked component IDs here. This will allow those fields to be saved as a config preset.
# Lines starting with a # are ignored.
# Component IDs can be found in the HTML (id="...") or in modules/ui.py (elem_id="...").
```

**Comment by ryenots** [comment]
Ah, I see. I had the wrong file open. The button to open this text file doesn't seem to work on Arch linux/KDE. This issue is present in base A1111 file opening features, so I assume it is a fault of KDE. Thanks for the help.
