### ISSUE TITLE
Feature Request : Ability to save Adetailer Separate Checkpoint

### ISSUE THREAD

**Issue by ZekeSora** [Zyin055/Config-Presets#73]
Couldn't find the value for this, it's saved when saving default settings though.
Could add them manually if anyone knows the values for those 2 options : (enable and set checkpoint)
![image](https://github.com/Zyin055/Config-Presets/assets/158193934/b2fa0c25-a359-457d-bc5f-1a302197c3df)

**Comment by Zyin055** [comment]
Multi-select fields, such as the checkpoint selector, are not supported with this extension.
