### ISSUE TITLE
How do I save prompt and neg prompts?

### ISSUE THREAD

**Issue by Loli-Kyn** [Zyin055/Config-Presets#74]
I have several models, and each has its own recommended prompts. Is there a way to save them too?

**Comment by Zyin055** [comment]
Sounds like a use case for the built in Styles feature.

If you're talking about LoRA prompts, the civitai extension saves the LoRA keywords.

**Comment by Loli-Kyn** [comment]
> Звучит как вариант использования встроенной функции «Стили».
> 
> Если вы говорите о подсказках LoRA, расширение civitai сохраняет ключевые слова LoRA.

Нет. Я не про LoRA, а про модель .safetensors. Яиспользую 2 и более модели, у которых разние подсказки для работы. Хотелось бы иметь функцию, которая бы сохраняла подскази и негативные подсказки

**Comment by Zyin055** [comment]
> No. I'm not talking about LoRA, but about the .safetensors model. I use 2 or more models that have different tips for working. I would like to have a function that would save prompts and negative prompts

You can add the prompt and negative prompt as saved fields using the "Add custom fields..." button.

**Comment by Loli-Kyn** [comment]
> > No. I'm not talking about LoRA, but about the .safetensors model. I use 2 or more models that have different tips for working. I would like to have a function that would save prompts and negative prompts
> 
> You can add the prompt and negative prompt as saved fields using the "Add custom fields..." button.

I clicked on this button and it opened the file "config-txt2img-custom..." and what should I do with it?

**Comment by Zyin055** [comment]
Read the instructions at the top of that text file.

**Comment by Loli-Kyn** [comment]
> Read the instructions at the top of that text file.

I read it, I don't get it.
