### ISSUE TITLE
Uncommenting controlnet components breaks extension

### ISSUE THREAD

**Issue by JcynR** [Zyin055/Config-Presets#76]
![image](https://github.com/Zyin055/Config-Presets/assets/22550885/8e0b8de5-60bc-46a5-9495-1bb9f22a61be)

If I uncomment these components for saving, the extension won't load.

**Comment by JcynR** [comment]
Same thing happens when uncommenting adetailer options for img2img tab. The preset ui disappears from the img2img tab.

**Comment by Zyin055** [comment]
They work for me on A1111 1.7.0, ControlNet v1.1.430, and ADetailer v23.11.1.

Please post the versions you have installed and the error in the console window.

**Comment by JcynR** [comment]
Using sd-webui-forge (https://github.com/lllyasviel/stable-diffusion-webui-forge)
with ControlNet integrated and adetailer v24.1.2

**Comment by Zyin055** [comment]
This is an Automatic1111 extension, not a Forge extension.
