### ISSUE TITLE
Adding an Extension Checkbox Option

### ISSUE THREAD

**Issue by ArmyOfPun1776** [Zyin055/Config-Presets#77]
This is not so much an issue as it is a question.

In the default options for Add/Remove you have the "txt2img_hr-checkbox" option there.  

I am using an extension called Dynamic Thresholding (https://github.com/mcmonkeyprojects/sd-dynamic-thresholding) and I've not had an issue adding the custom "elem_id"(s) that I want to the config file for my custom preset. The specific id for the checkbox, however, alludes me.  

The only reference in the code for the extension I can find in reference to the checkbox is a "elem_class".  Am I on the right track or is there something I'm missing?

Of course it's not too much of an issue to just enable the extension each time I spin up the UI, as all the internal extension options are saving as expected. It'd just be nice to have it enabled upon loading the custom preset.  

Thanks in advance.  Love the extension.

**Comment by ArmyOfPun1776** [comment]
![Screenshot 2024-02-20 074048](https://github.com/Zyin055/Config-Presets/assets/158170170/b99908c8-7323-44d3-9119-82711e18c996)

This is the only part of the code that I can find that specifically references a checkbox element.

**Comment by Zyin055** [comment]
It looks like that exension author has not included an ID for that checkbox. `elem_id` is the attribute you are looking for in the code, `elem_classes` is just for a CSS class. You can either ask the extension author to include an `elem_id` attribute for that checkbox, or you can edit that code and add `elem_id="whatever_id_name_here"` so you can target it.

**Comment by ArmyOfPun1776** [comment]
> It looks like that exension author has not included an ID for that checkbox. `elem_id` is the attribute you are looking for in the code, `elem_classes` is just for a CSS class. You can either ask the extension author to include an `elem_id` attribute for that checkbox, or you can edit that code and add `elem_id="whatever_id_name_here"` so you can target it.

Thanks.  That's what I figured.  I honestly wouldn't even know where to begin as far as adding the "target" myself.  I'll ask the creator if they'd be willing to do that.  Maybe try my hand at editing if I'm feeling brave. 

Thanks again for the fast reply.

**Comment by Zyin055** [comment]
Change the highlighted line in your screenshot to this:
```python
enabled = gr.Checkbox(value=False, label="Enable Dynamic Thresholding (CFG Scale Fix)", elem_classes=["dynthres-enabled"], elem_id="dynamic_thresholding_enable")
```
use `dynamic_thresholding_enable` to target it.

**Comment by ArmyOfPun1776** [comment]
You are a God amongst mortals! 

Thank you.  I was just looking up how to do this and you swooped in for the win.
