### ISSUE TITLE
Config Presets not showing on img2img tab

### ISSUE THREAD

**Issue by AllInOneMighty** [Zyin055/Config-Presets#78]
Updated to latest release, the tab does not show in Automatic1111.

My current set of extensions:

![image](https://github.com/Zyin055/Config-Presets/assets/1002605/9cbb977e-298d-4f23-89b6-0b1cc6c147d9)

I will try to disable them all except Config-Presets to see if it's one of them

**Comment by AllInOneMighty** [comment]
With only ControlNet & Config-Presets enabled, I get the config selection box only in `img2img`.

With only Config-Presets enabled, I **do not get any selection box** (the extension is invisible).

**Comment by Zyin055** [comment]
Check the console for errors relating to config presets.

This can happen when you have a saved preset looking for a component that doesn't exit on the web page anymore.

**Comment by AllInOneMighty** [comment]
Nothing appears in the logs. There is literally no dropdown/button anywhere on the img2img page.

![image](https://github.com/Zyin055/Config-Presets/assets/1002605/12e1ab3f-f99d-4c55-8b71-3c012e522b16)

**Comment by Zyin055** [comment]
What version of A1111 are you using? Are you using a Fork? I don't recognize some elements at the top of your screenshot.

**Comment by AllInOneMighty** [comment]
Automatic1111 v1.8.0. No fork.

I tried to fire it up with no extensions other than config-preset and got:

```
[ERROR][Config Presets] The txt2img component 'txt2img_controlnet_ControlNet-0_controlnet_enable_checkbox' could not be processed. This may be because you are running an outdated version of the Config-Presets extension, you included a component ID in the custom tracked components config file that does not exist, it no longer exists (if you updated an extension or Automatic1111), or is an invalid component (if this is the case, you need to manually edit the config file at S:\Install\sd.webui\webui\extensions\Config-Presets\config-txt2img-custom-tracked-components.txt or just delete it so it resets to defaults). This extension will not work until this issue is resolved.
Creating model from config: S:\Install\sd.webui\webui\configs\v1-inference.yaml
[ERROR][Config Presets] The img2img component 'img2img_controlnet_ControlNet-0_controlnet_enable_checkbox' could not be processed. This may be because you are running an outdated version of the Config-Presets extension, you included a component ID in the custom tracked components config file that does not exist, it no longer exists (if you updated an extension or Automatic1111), or is an invalid component (if this is the case, you need to manually edit the config file at S:\Install\sd.webui\webui\extensions\Config-Presets\config-img2img-custom-tracked-components.txt or just delete it so it resets to defaults). This extension will not work until this issue is resolved.
```

Tried again with `sd-webui-controlnet` and enabled `multidiffusion-upscaler-for-automatic1111`:

```
[ERROR][Config Presets] The img2img component 'MD-i2i-enable' could not be processed. This may be because you are running an outdated version of the Config-Presets extension, you included a component ID in the custom tracked components config file that does not exist, it no longer exists (if you updated an extension or Automatic1111), or is an invalid component (if this is the case, you need to manually edit the config file at S:\Install\sd.webui\webui\extensions\Config-Presets\config-img2img-custom-tracked-components.txt or just delete it so it resets to defaults). This extension will not work until this issue is resolved.
```

Apparently `multidiffusion-upscaler-for-automatic1111` updated their config and the field `MD-i2i-enable` was changed. I needed to update `MD-i2i-enable` to `MDV-i2i-enabled`  in the following files:
- `config-txt2img.json`
- `config-img2img.json`
- `config-img2img-custom-tracked-components.txt`

So it was not a problem with Config-Presets.

Might I suggest to ignore fields that are not found, rather than fail entirely and prevent the UI to show up?

Thank you!

**Comment by Zyin055** [comment]
Sometimes other extension authors like to change their component IDs which messes up config presets. We have an internal feature called synonyms that we use to deal with issues like this. I added synonyms for:
```
MD-t2i-enable -> MDV-t2i-enabled
MD-i2i-enable -> MDV-i2i-enabled
```
so that other people won't even notice this was an issue in the future. They can continue using the old ID and it'll still work as expected.

> Might I suggest to ignore fields that are not found, rather than fail entirely and prevent the UI to show up?

If only it were that easy. I wanted it to behave like that, but there are implementation problems with it.
