### ISSUE TITLE
The 4/13/2024 update breaks compatibility with Forge UI

### ISSUE THREAD

**Issue by scarfur** [Zyin055/Config-Presets#80]
The latest [update](https://github.com/Zyin055/Config-Presets?tab=readme-ov-file#4132024) breaks compatibility with [Forge](https://github.com/lllyasviel/stable-diffusion-webui-forge). The extension is no longer visible.

Related changes from the [changelog](https://github.com/Zyin055/Config-Presets?tab=readme-ov-file#changelog):
> * Updated for Automatic1111 1.9.0
> * This update to A1111 1.9.0 will likely not be backwards compatible with older A1111 versions.

As the [README](https://github.com/Zyin055/Config-Presets?tab=readme-ov-file#what-does-this-do) still states, Forge should be compatible (hopefully) again:
> Works with [stable-diffusion-webui-forge](https://github.com/lllyasviel/stable-diffusion-webui-forge).

//**edit: NVM** I found the line `[ERROR][Config Presets] ` regarding `The txt2img component 'txt2img_scheduler' could not be processed.`

**Comment by scarfur** [comment]
Deleting `config-img2img-custom-tracked-components.txt` and `config-txt2img-custom-tracked-components.txt`
and the `config-txt2img.json` & `config-img2img.json` did not resolved the issue. Maybe I am missing something else I could do?

**Comment by Zyin055** [comment]
I pushed an update that should fix the backwards compatibility issue since Forge is still on the 1.8.0 version of A1111.

**Comment by scarfur** [comment]
Solved - thank you very much 👍
