### ISSUE TITLE
Incompatibility with Tiled Diffusion

### ISSUE THREAD

**Issue by Westernnero** [Zyin055/Config-Presets#81]
Hi Zyin055! I've been using this ext for a while and appreciating your work! 

After updating the A1111 to 1.9.0, it seems that I cannot save or load any preset in the i2i page.

So I deleted the config-img2img.json and its custom-tracked-components file to let them initialize. Then as before, I uncommented the fields under Tiled Diffusion (extension) and Tiled Diffusion - Tiled VAE.
![image](https://github.com/Zyin055/Config-Presets/assets/40510735/30861ff2-5715-47c8-b693-f7b701b5fece)

Then if I try to save any preset, it raises error.
![image](https://github.com/Zyin055/Config-Presets/assets/40510735/04245a3a-d46c-4373-8b07-1cf8c09e8d91)

Nor can I load my previous presets. Though no error info raised, it just doesn't work.

Here are some error info I can find, hope them can help:
![image](https://github.com/Zyin055/Config-Presets/assets/40510735/6a051b03-cf95-4e4e-8948-9d9c77d41d48)

**Comment by Zyin055** [comment]
I don't have the Tiled Diffusion extension installed anymore. Can you verify that the IDs you uncommented still exist in the HTML? It's been a while since I added those IDs to the template, so it's possible the extension author had them changed. You can use your browsers dev tools (F12) to inspect the HTML and use Ctrl-F to search.

**Comment by Zyin055** [comment]
@Westernnero ^

**Comment by Westernnero** [comment]
sry for a late reply. I've searched the IDs in the latest version A1111 i2i page.
However, excect for that the sampler now has two fields, "sampling""scheduler", the other IDs seems unchanged.
And even if I just keep one or two of the IDs (which are definitely there, according to dev tools) of Tiled Diffusion to try to enable Config Preset in the i2i page, it did not work. Nor can I click the save button.
Thank you for your instruction anyway. I'm already very rarely using Tiled Diffusion, too. So it doesn't matter. And still convenient in t2i page.

**Comment by KiyonakaNata** [comment]
Hello Zyin055,

I have found the Config-Presets to be incredibly useful and have been a long-time user.
I was also troubled by the issue with enabling Tiled Diffusion. 
Although this issue has been marked as closed, I would like to add a solution here.

Config-Presets is an excellent tool, and I hope it continues to be used by everyone even after the UI changes in version 1.9 and later.

#### Cause:
- In version 1.9, the UI change resulted in a change of ID for `enabled`.
- The IDs like `MD-t2i-enabled` were used as accordion IDs and were causing errors.
- Changing it to `XXX"-checkbox"` resolved the issue without problems.

#### Solution:
For `config-txt2img-custom-tracked-components.txt` and `config-txt2img.json`:

```diff
- MD-t2i-enabled
+ MD-t2i-enabled-checkbox

- MDV-t2i-enabled
+ MDV-t2i-enabled-checkbox
```
For `config-img2img-custom-tracked-components.txt` and `config-img2img.json`:

```diff

- MD-i2i-enabled
+ MD-i2i-enabled-checkbox

- MDV-i2i-enabled
+ MDV-i2i-enabled-checkbox
```
