### ISSUE TITLE
Support for ADetailer v24.6.0

### ISSUE THREAD

**Issue by scyl** [Zyin055/Config-Presets#86]
I am not 100% sure, but after updating ADetailer to v24.6.0, I got an error from Config-Presets likely because some component IDs have been changed? If that is the case, is it possible to update the fields in the IDs in `config-txt2img-custom-tracked-component.txt` please?

**Comment by Zyin055** [comment]
If you could provide details as to which ID changed (and what it changed to), or a link to the ADetailer commit that changed it, it would greatly help.

**Comment by scyl** [comment]
I am not very familiar with how the code works, but looking at the commits, I believe this one is the most likely candidate? https://github.com/Bing-su/adetailer/commit/2ace2759b8c330dd0cdfa67198fc5dcccad018ed

If that is the commit, then please see https://github.com/Bing-su/adetailer/commit/479f5f4a2e88f6b5db0b323668a2cfaf464ded41 as well as the names were updated again in this commit.

**Comment by Zyin055** [comment]
At first glance I don't see any changes in those 2 commits that would change an existing component ID.

Look at your A1111 console for errors relating to Config Presets and see which ID it complains about.

**Comment by scyl** [comment]
This is the error I got 

> [ERROR][Config Presets] The txt2img component 'script_txt2img_adetailer_ad_enable' could not be processed. This may be because you are running an outdated version of the Config-Presets extension, you included a component ID in the custom tracked components config file that does not exist, it no longer exists (if you updated an extension or Automatic1111), or is an invalid component (if this is the case, you need to manually edit the config file at D:\Programs\Stable Diffusion WebUI\webui\extensions\Config-Presets\config-txt2img-custom-tracked-components.txt or just delete it so it resets to defaults). This extension will not work until this issue is resolved.

maybe it's this commit? https://github.com/Bing-su/adetailer/commit/a479f60f405481a37c98c1b08534610de9e9e05b

**Comment by scyl** [comment]
Updated the component ID to `script_txt2img_adetailer_ad_main_accordion` seem to have fixed the issue.

Would be nice to add the new `ad_tab_enable` components to the file too.

**Comment by scyl** [comment]
Nevermind getting error `assert isinstance(
AssertionError: <class 'gradio.layouts.Accordion'> Component with id 142 not a valid input component.` with `script_txt2img_adetailer_ad_main_accordion`

**Comment by Zyin055** [comment]
The error was because ADetailer added an enable checkbox to the accordion, and renamed the already existing enable checkboxes for each of the 2 tabs. I added an exception so it'll treat your `script_txt2img_adetailer_ad_enable` ID in your config files as if it were the new corresponding ID: `script_txt2img_adetailer_ad_main_accordion`

Update Config Presets and the issue should be resolved.

**Comment by scyl** [comment]
I have updated but am getting the following error when I try to apply a config
>Traceback (most recent call last):
  File "D:\Programs\Stable Diffusion WebUI\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Programs\Stable Diffusion WebUI\system\python\lib\site-packages\gradio\blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\Programs\Stable Diffusion WebUI\system\python\lib\site-packages\gradio\blocks.py", line 1233, in preprocess_data
    assert isinstance(
AssertionError: <class 'gradio.layouts.Accordion'> Component with id 2943 not a valid input component.

**Comment by Zyin055** [comment]
Their accordion component uses a separate hidden checkbox ID, so I swapped it to use that. Should work now.

**Comment by scyl** [comment]
Thanks for the help, and update, it is working fine now!

**Comment by ENTPRESTIGIOUS** [comment]
Got the same issue, just updated.
```
[ERROR][Config Presets] The txt2img component 'script_txt2img_adetailer_ad_enable' could not be processed. This may be because you are running an outdated version of the Config-Presets extension, you included a component ID in the custom tracked components config file that does not exist, it no longer exists (if you updated an extension or Automatic1111), or is an invalid component (if this is the case, you need to manually edit the config file at D:\ai\StabilityMatrix\Packages\stable-diffusion-webui\extensions\Config-Presets\config-txt2img-custom-tracked-components.txt or just delete it so it resets to defaults). This extension will not work until this issue is resolved.
2024-08-07 11:36:28,321 - AnimateDiff - INFO - Hacking i2i-batch.
2024-08-07 11:36:28,352 - ControlNet - INFO - ControlNet UI callback registered.
[ERROR][Config Presets] The img2img component 'script_img2img_adetailer_ad_enable' could not be processed. This may be because you are running an outdated version of the Config-Presets extension, you included a component ID in the custom tracked components config file that does not exist, it no longer exists (if you updated an extension or Automatic1111), or is an invalid component (if this is the case, you need to manually edit the config file at D:\ai\StabilityMatrix\Packages\stable-diffusion-webui\extensions\Config-Presets\config-img2img-custom-tracked-components.txt or just delete it so it resets to defaults). This extension will not work until this issue is resolved.
```

**Comment by rkfg** [comment]
Doesn't work for me, still returns `AssertionError: <class 'gradio.layouts.Accordion'> Component with id 2377 not a valid input component.`. However, another extension that uses the same approach (`Dynamic Thresholding (CFG Scale Fix)`) reacts correctly. I have `script_img2img_adetailer_ad_main_accordion` added to `config-img2img-custom-tracked-components.txt`. Using `script_img2img_adetailer_ad_enable` instead breaks the extension with `[ERROR][Config Presets] The img2img component 'script_img2img_adetailer_ad_enable' could not be processed. This may be because you are running an outdated version of the Config-Presets extension...`.

Same Accordion error happens for `soft_inpainting_enabled` which I'd also love to use.

**Comment by Zyin055** [comment]
Just don't use `script_img2img_adetailer_ad_enable`, it's the old ID which is no longer used by ADetailer. Use `script_img2img_adetailer_ad_main_accordion-checkbox` instead.

`soft_inpainting_enabled` has a similar issue, the accordion uses a hidden checkbox labeled `soft_inpainting_enabled-checkbox` so use that ID instead.

**Comment by rkfg** [comment]
Thank you, I tried `script_img2img_adetailer_ad_main_accordion-visible-checkbox` and it didn't work, didn't know that `-visible` should be omitted. Now both work.
