### ISSUE TITLE
Disappeared tab

### ISSUE THREAD

**Issue by However1111** [Zyin055/Config-Presets#87]
Config-preset tab is suddenly disappeared after I updated the all extensions, and when I disabled the all extensions except "Config-presets" it doesn't work
The tab disappeared, but the Config-presets folder still there.
What can I do ?

**Comment by Zyin055** [comment]
Check the console on startup for any errors relating to config presets. Also post your current A1111 version.

**Comment by harukaxxxx** [comment]
In my case, I have noticed an error message in the console, just delete **custom-tracked-components** files and edit the adetailer component name in the preset file, everything works great like before.
```
[ERROR][Config Presets] The txt2img component 'script_txt2img_adetailer_ad_enable' could not be processed. This may be because you are running an outdated version of the Config-Presets extension, you included a component ID in the custom tracked components config file that does not exist, it no longer exists (if you updated an extension or Automatic1111), or is an invalid component (if this is the case, you need to manually edit the config file at D:\AiWorks\Image\stable-diffusion-webui-forge\extensions\Config-Presets\config-txt2img-custom-tracked-components.txt or just delete it so it resets to defaults). This extension will not work until this issue is resolved.
```
