### ISSUE TITLE
[Feature Request] Refresh button

### ISSUE THREAD

**Issue by wywywywy** [Zyin055/Config-Presets#9]
In A1111, there's a refresh button next to the Checkpoints dropdown list.

Config-Presets could implement the same UI, so that when we change the `config.json`, we can just click a button to reload the entries without having to restart the whole thing.

**Comment by Gerschel** [comment]
Tip for @Zyin055 : https://github.com/gradio-app/gradio/discussions/2848

**Comment by Zyin055** [comment]
c993d136258c7221c4aa3a103c1767dcc3ed6deb
Adding/removing presets is now available from within the Web UI directly, which will auto update the dropdown. If you decide to edit the config.json file manually you'll still need to refresh Gradio though.
