### ISSUE TITLE
Soft Inpainting to custom config

### ISSUE THREAD

**Issue by slusht** [Zyin055/Config-Presets#90]
Is it possible to add Soft Inpainting settings to the custom fields or does that count as an accordion style ID? I've located the ID's in the HTML as (among the slider options within the drop down):

#soft_inpainting_enabled-checkbox
#soft_inpainting_enabled

EDIT:  I've tried saving them to the config-img2img-custom-tracked-components file, saved, booted and they haven't appeared with the other IMG2IMG selections.

**Comment by Zyin055** [comment]
It worked when I tried it. These are the IDs I used:
```
# Soft Inpainting:
#soft_inpainting_enabled-checkbox
#mask_blend_power
#mask_blend_scale
#inpaint_detail_preservation
#composite_mask_influence
#composite_difference_threshold
#composite_difference_contrast
```
