### ISSUE TITLE
QUESTION: What is the config id to save the Seed?

### ISSUE THREAD

**Issue by merket** [Zyin055/Config-Presets#93]
What is the config id to save the generation Seed?
I see these id options but they say they're subseed. How can I save my image generation sees as well, along with the preset?

#txt2img_subseed_show
#txt2img_subseed
#txt2img_subseed_strength
#txt2img_seed_resize_from_w
#txt2img_seed_resize_from_h

**Comment by Zyin055** [comment]
You can put `txt2img_seed` in that file to enable it.
